### ISSUE TITLE
Running 'python astro_rcnn.py detect example' on windows and it gives a Keyword 'CLASS_ID' not found error.

### ISSUE THREAD

**Issue by hibajamal** [burke86/astro_rcnn#2]
![Untitled](https://user-images.githubusercontent.com/35984866/69147817-bdc00f00-0af4-11ea-9472-d6132a0d10e8.png)

**Comment by hibajamal** [comment]
Also, where is the mask.fits file btw

**Comment by burke86** [comment]
Thank you for opening this issue. The mask files should only be required in "train" or "assess" mode (need a ground truth mask), not in "detect" (inference) mode. Please checkout the latest version for the fix.

**Comment by hibajamal** [comment]
Thank you!
